main page
htmlacademy-adaptive/1580745-cat-energy-22 pull request #2
Opened 2021-04-02 09:20 UTC by AleksandrKisler

2021-04-02 16:14 UTC, DoberBober commented on source/index.html
> +    <div class="header__logo">
Элемент вне блока. `header__***` должен быть предком `header`. В данном случае тегу `header` на 8 строке добавь класс `header`.

2021-04-02 16:14 UTC, DoberBober commented on source/index.html
> +    <div class="header__logo">
Логотип - это ссылка же.

2021-04-02 16:15 UTC, DoberBober commented on source/index.html
> +    <div class="company__name">
Элемент вне блока.

2021-04-02 16:15 UTC, DoberBober commented on source/index.html
> +    <button class="main__toggle--xs">
1. Элемент вне блока.
2. Модификатор без основного класса (если стоит класс `main__toggle--xs`, то должен быть и класс `main__toggle`).

2021-04-02 16:15 UTC, DoberBober commented on source/index.html
> +    <nav class="main__nav">
Тоже элемент вне блока.

2021-04-02 16:16 UTC, DoberBober commented on source/index.html
> +      <a href="#" class="nav__link">главная</a>
И тут.

2021-04-02 16:16 UTC, DoberBober commented on source/index.html
> +    <div class="billboard__description">
Тоже.

2021-04-02 16:16 UTC, DoberBober commented on source/index.html
> +  <section class="programs__list">
И эти элементы.

2021-04-02 16:17 UTC, DoberBober commented on source/index.html
> +      <div class="program__item--body">
Здесь и у двоих следующих модификаторы без основного класса.

2021-04-02 16:17 UTC, DoberBober commented on source/index.html
> +  <section class="how_its_work">
Вот тут верно: ты выделил блок `how_its_work`, а внутри него лежат его элементы (`how_its_work__title`, `how_its_work__list`).

Только название надо переименовать. Сделай через дефисы (`how-its-work`).

2021-04-02 16:18 UTC, DoberBober commented on source/index.html
> +        <img src="img/sheet.svg" class="item__image" alt="листок">
Тоже вне блока.

2021-04-02 16:18 UTC, DoberBober commented on source/index.html
> +  <section class="example">
Example тоже верный.

2021-04-02 16:18 UTC, DoberBober commented on source/index.html
> +      <ul class="progress__list">
Ну дальше тоже, в общем.

2021-04-02 16:19 UTC, DoberBober commented on source/index.html
> +        <div class="academy__logotype">
Div -> A. И href пропиши на лендинг интенсива.

2021-04-02 16:20 UTC, DoberBober requested changes
По БЭМу очень много ошибок. Советую пересмотреть лекцию и почитать доп.материалы. Если понадобится помощь, пиши. Постараюсь объяснить на пальцах.
При проверке задания используй https://yoksel.github.io/html-tree/
Вставляешь туда свой html-код и он выделяет места с ошибками.

2021-04-05 07:05 UTC, AleksandrKisler reviewed
fix

2021-04-05 15:33 UTC, DoberBober commented on source/index.html
> +          <a class="main-navigation__link active">главная</a>
Вообще хорошо было бы, если бы ты убрал `active` и написал `main-navigation__link--active`.

2021-04-05 15:35 UTC, DoberBober commented on source/index.html
> +  <section class="programs">
Блок `programs` называется, а элементы `program`. Поправь.

2021-04-05 15:35 UTC, DoberBober commented on source/index.html
> +    <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
`main-navigation__toggle`.

2021-04-05 15:36 UTC, DoberBober commented on source/index.html
> +          <p class="program--item-text">
`program__item-text`.

2021-04-05 15:36 UTC, DoberBober commented on source/index.html
> +            <span class="catalog__name-arrow">
Элемент вне блока.

2021-04-05 15:36 UTC, DoberBober commented on source/index.html
>            <span class="catalog__name">каталог slim
Элемент вне блока.

2021-04-05 15:37 UTC, DoberBober requested changes
Не все ошибки исправил. Ниже в разметке есть ещё. Не забывай проверять через https://yoksel.github.io/html-tree/

![image](https://user-images.githubusercontent.com/18398812/113592501-ed19e200-963d-11eb-99da-2067ae5f01d7.png)
![image](https://user-images.githubusercontent.com/18398812/113592508-ef7c3c00-963d-11eb-805a-55655ba0288f.png)

2021-04-06 08:17 UTC, merged